---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, netapp console 
summary: NetApp Console需要通过 Google Cloud 服务帐户访问Google Cloud NetApp Volumes API 并获得正确的权限。 
---
= 设置Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console需要通过 Google Cloud 服务帐户获得正确的权限。

完成以下任务，以便 NetApp Console 可以访问您的 Google Cloud 项目。


NOTE: 您可以使用 Google Cloud 控制台或 gcloud CLI 执行这些任务。要使用 gcloud CLI，您必须先link:https://cloud.google.com/sdk/docs/install-sdk["已安装 Google Cloud CLI"^]。

* 如果您还没有服务帐户，请创建一个新的。
* 允许冒充他人访问。
* 在共享项目中授予 IAM 角色。




[[set-up-a-service-account]]
== 设置服务帐户


NOTE: Google Cloud 项目权限更改可能需要几分钟才能生效。

. 在 Google Cloud 控制台中， https://console.cloud.google.com/iam-admin/serviceaccounts["前往服务帐户页面"^] 。
. 单击*选择项目*，选择您的项目，然后单击*打开*。
. 要创建服务帐户，请执行以下操作：
+
.. 点击*创建服务帐户*。
.. 输入服务帐户名称（友好显示名称）和描述。
+
Google Cloud Console 根据此名称生成服务帐户 ID。如有必要，请编辑 ID - 您以后无法更改 ID。

.. 点击“创建并继续”。
.. 从角色列表中，选择 *Google Cloud NetApp Volumes 管理员* 或 *Google Cloud NetApp Volumes 查看者* 角色。
.. 选择*继续*。
+
或者，您可以使用 gcloud CLI 分配角色：

+
[source, cli]
----
gcloud projects add-iam-policy-binding <YOUR_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----
.. 授予此服务帐户模拟访问权限：credentials-sa@wf-production-netapp.iam.gserviceaccount.com。有关详细信息，请参阅 https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["创建自签名 JSON Web Token (JWT)"^]。
+
NetApp拥有的服务帐户用于请求一个短期访问令牌，该令牌允许您以该服务帐户的身份进行操作，而无需访问其私钥。

+
或者，您可以使用 gcloud CLI 授予模拟访问权限：

+
[source, cli]
----
gcloud iam service-accounts add-iam-policy-binding <YOUR_SA_EMAIL> --member="serviceAccount:credentials-sa@wf-production-netapp.iam.gserviceaccount.com" --role="roles/iam.serviceAccountTokenCreator" --project=<YOUR_PROJECT_ID>
----
.. 点击页面底部的“完成”按钮，然后继续下一步。






[[shared-vpc]]
== 共享 VPC

在将使用服务帐户的每个其他 Google Cloud 项目中，请执行以下操作：

. 在_IAM 页面_中，从项目下拉菜单中选择共享 VPC 主机项目。
. 单击“添加主体”。
. 在“新主体”字段中，输入您的服务帐户的电子邮件地址。
. 从“选择角色”下拉菜单中，选择“* Google Cloud NetApp Volumes管理员*”角色。
. 单击“保存”。
+
或者，您可以使用 gcloud CLI 添加 IAM 策略绑定：

+
[source, cli]
----
gcloud projects add-iam-policy-binding <SHARED_VPC_HOST_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----


详细步骤请参考Google Cloud文档：

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["创建和管理服务帐户"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Google Cloud NetApp Volumes角色和权限"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["授予、更改和撤销对资源的访问权限"^]




[[troubleshooting]]
== 故障排除

如果遇到错误，可能会强制执行 *iam.disableCrossProjectServiceAccountUsage* 策略。要解决此问题，请执行以下操作：

. 在 Google Cloud 控制台中，转到 https://console.cloud.google.com/iam-admin/orgpolicies["组织政策页面"^]。
. 找到“禁用跨项目服务帐户使用”策略并将其禁用。


.下一步是什么？
link:task-add-roles.html["分配Google Cloud NetApp Volumes角色"]。
